export interface ATMLocation {
  id: string,
  position: { lat: number, lng: number },
  title: string,
  address: string,
  city: string,
  state: string,
  zip: number,
  phone: string,
}

export const ATM_LOCATIONS: ATMLocation[] = [
  {
    id: 'ChIJsT5WeseMUocRIhsDVNprecA',
    position: { lat: 40.70431, lng: -111.9772035 },
    title: 'Phillips 66',
    address: '3100 S 3596 W',
    city: 'Salt Lake City',
    state: 'UT',
    zip: 84119,
    phone: '(801) 975-0922',
  },
  {
    id: 'ChIJqVxI1TWPUocR-09k2DyxHHY',
    position: { lat: 40.5873117, lng: -111.9603154 },
    title: 'Express Mart',
    address: '2729 W 9000 S',
    city: 'West Jordan',
    state: 'UT',
    zip: 84088,
    phone: '(801) 566-9280',
  },
  // {
  //   id: '',
  //   position: { lat: 37.0748313, lng: -113.5538578 },
  //   title: "Mr. D's Chevron",
  //   address: '1946 S River Road',
  //   city: 'St George',
  //   state: 'UT',
  //   zip: 84790,
  //   phone: '(435) 619-2502',
  // },
  // {
  //   id: '',
  //   position: { lat: 40.4025069, lng: -111.853028 },
  //   title: 'Quail Lake Chevron',
  //   address: '4390 W State St',
  //   city: 'Hurricane',
  //   state: 'UT',
  //   zip: 84737,
  //   phone: '(435) 635-2243',
  // },
  // {
  //   id: '',
  //   position: { lat: 40.6945514, lng: -111.5471557 },
  //   title: 'Hyatt Place Park City',
  //   address: '4377 N Hwy 224',
  //   city: 'Park City',
  //   state: 'UT',
  //   zip: 84098,
  //   phone: '(435) 776-1234',
  // },
  // {
  //   id: '',
  //   position: { lat: 40.3873893, lng: -111.8792258 },
  //   title: 'All About Fuel & Food',
  //   address: '1750 W Main St.',
  //   city: 'Lehi',
  //   state: 'UT',
  //   zip: 84043,
  //   phone: '(801) 331-8787',
  // },
  // {
  //   id: '',
  //   position: { lat: 38.2940108, lng: -112.6488477 },
  //   title: 'Kevins Conoco',
  //   address: '1434 N 300 West',
  //   city: 'Beaver',
  //   state: 'UT',
  //   zip: 84713,
  //   phone: '(435) 438-5049',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Cesars Royal Lounge Babershop',
  //   address: '4889 State St',
  //   city: 'Murray',
  //   state: 'UT',
  //   zip: 84107,
  //   phone: '(801)266-2571',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Dutchmans Market',
  //   address: '2300 Santa Clara Dr.',
  //   city: 'Santa Clara',
  //   state: 'UT',
  //   zip: 84765,
  //   phone: '(435) 628-8482',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Village Food Mart',
  //   address: '1238 W Village Main Dr.',
  //   city: 'West Valley',
  //   state: 'UT',
  //   zip: 84119,
  //   phone: '(801) 244-5566',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Handy Pantry',
  //   address: '1252 W 400 S',
  //   city: 'Salt Lake City',
  //   state: 'UT',
  //   zip: 84104,
  //   phone: '',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Mercado Las Americas',
  //   address: '1187 N 1200 W',
  //   city: 'Orem',
  //   state: 'UT',
  //   zip: 84057,
  //   phone: '(801) 403-6634',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Neptuno Event Center',
  //   address: '1175 North 1200 West',
  //   city: 'Orem',
  //   state: 'UT',
  //   zip: 84057,
  //   phone: '(801) 369-1249',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Ksk Quick Stop',
  //   address: '3971 S 1900 W',
  //   city: 'Roy',
  //   state: 'UT',
  //   zip: 84067,
  //   phone: '(801) 731-1311',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Holiday Inn Express - Zion',
  //   address: '2450 N Town Center Dr.',
  //   city: 'Washington',
  //   state: 'UT',
  //   zip: 84780,
  //   phone: '',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Alchemy Arcade',
  //   address: '1435 S State St',
  //   city: 'Salt Lake City',
  //   state: 'UT',
  //   zip: 84115,
  //   phone: '(801) 455-3403',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Chillys Chevron',
  //   address: '815 E 100 N',
  //   city: 'Nephi',
  //   state: 'UT',
  //   zip: 84648,
  //   phone: '(435) 864-2313',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Ss Land',
  //   address: '6157 S Highland Dr',
  //   city: 'Holladay',
  //   state: 'UT',
  //   zip: 84121,
  //   phone: '',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Gotam',
  //   address: '1155 N Main St',
  //   city: 'Layton',
  //   state: 'UT',
  //   zip: 84014,
  //   phone: '(385) 216-6518',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Eagles Landing Green River',
  //   address: '1085 E Main St',
  //   city: 'Green River',
  //   state: 'UT',
  //   zip: 84525,
  //   phone: '(435) 564-3495',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Eagles Landing Green River Rear',
  //   address: '1085 E Main St',
  //   city: 'Green River',
  //   state: 'UT',
  //   zip: 84525,
  //   phone: '(435) 564-3495',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Food Elwood 80232',
  //   address: '5175 W 9600 N',
  //   city: 'Elwood',
  //   state: 'UT',
  //   zip: 84337,
  //   phone: '(435) 257-4710',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Foods Nephi Texaco 80233',
  //   address: '2050 S Main St',
  //   city: 'Nephi',
  //   state: 'UT',
  //   zip: 84648,
  //   phone: '(435) 623-2644',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Foods Nephi Chevron 80234',
  //   address: '2087 S Main St',
  //   city: 'Nephi',
  //   state: 'UT',
  //   zip: 84648,
  //   phone: '(435) 623-2922',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'White Raven Tattoo',
  //   address: '7692 S 100 W',
  //   city: 'Midvale',
  //   state: 'UT',
  //   zip: 84047,
  //   phone: '(385) 274-2349',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Eastern Groceries & Deli',
  //   address: '1616 W 3500 S',
  //   city: 'West Valley City',
  //   state: 'UT',
  //   zip: 84119,
  //   phone: '801-975-7805',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Tru Buy',
  //   address: '357 E 3300 S.',
  //   city: 'South Salt Lake',
  //   state: 'UT',
  //   zip: 84115,
  //   phone: '',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'D&D Smokes & More',
  //   address: '435 N Aviation Way',
  //   city: 'Cedar City',
  //   state: 'UT',
  //   zip: 84115,
  //   phone: '(435) 865-6188',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Quality Inn Cedar City',
  //   address: '250 N 1100 W',
  //   city: 'Cedar City',
  //   state: 'UT',
  //   zip: 84721,
  //   phone: '(435) 586-2082',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Fosters Market',
  //   address: '4617 N Minersville Hwy',
  //   city: 'Cedar City',
  //   state: 'UT',
  //   zip: 84721,
  //   phone: '(435) 263-0440',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Milford Chevron',
  //   address: '402 S. Main St',
  //   city: 'Milford',
  //   state: 'UT',
  //   zip: 84751,
  //   phone: '435-387-5566',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Cedar Band Travel Plaza',
  //   address: '3748 S. Old Highway 91',
  //   city: 'Cedar City',
  //   state: 'UT',
  //   zip: 84720,
  //   phone: '(435) 586-5542',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Ramada Cedar City',
  //   address: '1575 W 200 N',
  //   city: 'Cedar City',
  //   state: 'UT',
  //   zip: 84720,
  //   phone: '(435) 267-0856',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Am 2 Pm',
  //   address: '9447 S. Union Square',
  //   city: 'Sandy',
  //   state: 'UT',
  //   zip: 84070,
  //   phone: 3853472069,
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Foods-Washington',
  //   address: '260 South Green Springs Drive',
  //   city: 'Washington',
  //   state: 'UT',
  //   zip: '84780-0000',
  //   phone: '(435) 674-9575',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Slick Rock Cinemas 3',
  //   address: '580 Kane Creek Boulevard',
  //   city: 'Moab',
  //   state: 'UT',
  //   zip: 84532,
  //   phone: '(435) 259-5925',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Coffee Roasters',
  //   address: '90 North Main Street',
  //   city: 'Moab',
  //   state: 'UT',
  //   zip: 84532,
  //   phone: '(435) 259-2725',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Canyonlands Field Airport',
  //   address: '110 Aviation Way',
  //   city: 'Moab',
  //   state: 'UT',
  //   zip: 84532,
  //   phone: '(435) 259-4849',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Canyonlands Inn',
  //   address: '16 S. Main Street',
  //   city: 'Moab',
  //   state: 'UT',
  //   zip: 84532,
  //   phone: '(435) 259-2300',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Shirttail',
  //   address: 'Highway 191 Junction 95',
  //   city: 'Blanding',
  //   state: 'UT',
  //   zip: 84511,
  //   phone: '(435) 678-4003',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Southway',
  //   address: '651 South Main',
  //   city: 'Blanding',
  //   state: 'UT',
  //   zip: 84511,
  //   phone: '(435) 678-9916',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Canyonlands Conoco',
  //   address: '433 North Main',
  //   city: 'Monticello',
  //   state: 'UT',
  //   zip: 84535,
  //   phone: '(435) 587-2485',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'White Raven Tattoo',
  //   address: '7692 Maple Street',
  //   city: 'Midvale',
  //   state: 'UT',
  //   zip: 84047,
  //   phone: '385-274-2351',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Big Mountain Lodge',
  //   address: '161 East Main Street',
  //   city: 'Ferron',
  //   state: 'UT',
  //   zip: 84523,
  //   phone: '(435) 749-2646',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Newgate Mall-Food Court',
  //   address: '3651 Wall Avenue',
  //   city: 'Ogden',
  //   state: 'UT',
  //   zip: 84405,
  //   phone: '(801) 621-1162',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Newgate Mall-Center Court',
  //   address: '3651 Wall Avenue',
  //   city: 'Ogden',
  //   state: 'UT',
  //   zip: 84405,
  //   phone: '(801) 621-1162',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Newgate Mall-Cinemark',
  //   address: '3651 Wall Avenue',
  //   city: 'Ogden',
  //   state: 'UT',
  //   zip: 84405,
  //   phone: '(801) 621-1162',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Wee Blu Inn',
  //   address: '39 North Main Street',
  //   city: 'Payson',
  //   state: 'UT',
  //   zip: 84651,
  //   phone: '(801) 465-9071',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Ah Enterprises-Roy',
  //   address: '5348 South 1900 West',
  //   city: 'Roy',
  //   state: 'UT',
  //   zip: 84067,
  //   phone: '(801) 599-3786',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Ah Enterprises-Salt Lake City',
  //   address: '89 West 3300 South',
  //   city: 'Salt Lake City',
  //   state: 'UT',
  //   zip: 84115,
  //   phone: '(801) 599-3786',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Noble Cash Services-Event Atm 1',
  //   address: '87 West Casi Way',
  //   city: 'Saratoga Springs',
  //   state: 'UT',
  //   zip: 84045,
  //   phone: '(801) 232-9594',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Noble Cash Services-Event Atm 2',
  //   address: '87 West Casi Way',
  //   city: 'Saratoga Springs',
  //   state: 'UT',
  //   zip: 84045,
  //   phone: '(801) 232-9594',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Foods-Cedar City 812 W',
  //   address: '812 West 200 North',
  //   city: 'Cedar City',
  //   state: 'UT',
  //   zip: 84721,
  //   phone: '(435) 586-3287',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Foods-Cedar City 734 S',
  //   address: '734 South Main',
  //   city: 'Cedar City',
  //   state: 'UT',
  //   zip: 84720,
  //   phone: '(435) 586-1344',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Foods-Cedar City 1944 N',
  //   address: '1944 North Main',
  //   city: 'Cedar City',
  //   state: 'UT',
  //   zip: 84721,
  //   phone: '(435) 586-2681',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Foods-Parowan',
  //   address: '1661 West 200 South',
  //   city: 'Parowan',
  //   state: 'UT',
  //   zip: 84761,
  //   phone: '(435) 477-9991',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Foods-Alton',
  //   address: '1370 West Highway 14',
  //   city: 'Alton',
  //   state: 'UT',
  //   zip: 84710,
  //   phone: '435-638-3400',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Foods-Panguitch',
  //   address: '195 North Main',
  //   city: 'Panguitch',
  //   state: 'UT',
  //   zip: 84759,
  //   phone: '435-676-8730',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Foods-Milford',
  //   address: '437 South Main',
  //   city: 'Milford',
  //   state: 'UT',
  //   zip: 84751,
  //   phone: '(435) 387-2890',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Foods-St. George',
  //   address: '948 East Brigham Road',
  //   city: 'St. George',
  //   state: 'UT',
  //   zip: 84790,
  //   phone: '(435) 522-7005',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'The Rest',
  //   address: '331 South Main Street',
  //   city: 'Salt Lake City',
  //   state: 'UT',
  //   zip: 84111,
  //   phone: '(801) 532-4452',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Food-Panguitch N Main',
  //   address: '595 North Main Street',
  //   city: 'Panguitch',
  //   state: 'UT',
  //   zip: 84759,
  //   phone: '(801) 403-6634',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Food-Panguitch E Center',
  //   address: '575 East Center Street',
  //   city: 'Panguitch',
  //   state: 'UT',
  //   zip: 84759,
  //   phone: '(801) 403-6634',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Food-Heber',
  //   address: '1590 South Highway 40',
  //   city: 'Heber City',
  //   state: 'UT',
  //   zip: 84032,
  //   phone: '(801) 403-6634',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Food-Salina South',
  //   address: '1645 South State',
  //   city: 'Salina',
  //   state: 'UT',
  //   zip: 84654,
  //   phone: '(801) 403-6634',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Food-Salina',
  //   address: '1415 South State',
  //   city: 'Salina',
  //   state: 'UT',
  //   zip: 84654,
  //   phone: '(801) 403-6634',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Harts Gas & Food-Elsinore',
  //   address: '250 South Highway 89',
  //   city: 'Elsinore',
  //   state: 'UT',
  //   zip: 84724,
  //   phone: '(801) 403-6634',
  // },
  // {
  //   id: '',
  //   position: { lat: 0, lng: 0 },
  //   title: 'Smokes Etc',
  //   address: '1019 Washington Boulevard',
  //   city: 'Ogden',
  //   state: 'UT',
  //   zip: 84404,
  //   phone: '(801) 770-2955',
  // },
]